'use strict';
const http=require('node:http'), fs=require('node:fs'), path=require('node:path');
const {randomUUID,createHash}=require('node:crypto');
const {createStore,ValidationError}=require('./storage.cjs'), engine=require('./engine.js');
const MAX_BODY=256*1024, STATIC=new Map([['/',['index.html','text/html; charset=utf-8']],['/index.html',['index.html','text/html; charset=utf-8']],['/styles.css',['styles.css','text/css; charset=utf-8']],['/fixes.css',['fixes.css','text/css; charset=utf-8']],['/app.js',['app.js','text/javascript; charset=utf-8']],['/engine.js',['engine.js','text/javascript; charset=utf-8']]]);
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}} class ConflictError extends Error{}
const trim=(v,max,label)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new ValidationError(`${label}: 1-${max} caracteres.`);return v.trim();};
const optional=(v,max,label)=>{if(v===undefined||v===null)return '';if(typeof v!=='string'||v.trim().length>max)throw new ValidationError(`${label}: máximo ${max} caracteres.`);return v.trim();};
const int=(v,min,max,label)=>{if(!Number.isInteger(v)||v<min||v>max)throw new ValidationError(`${label}: entero entre ${min} y ${max}.`);return v;};
const iso=(v,label)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(v))throw new ValidationError(`${label}: fecha ISO UTC real.`);const match=v.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})/),[year,month,day,hour,minute,second]=match.slice(1).map(Number),parsed=new Date(Date.UTC(year,month-1,day,hour,minute,second));if(hour>23||minute>59||second>59||parsed.getUTCFullYear()!==year||parsed.getUTCMonth()!==month-1||parsed.getUTCDate()!==day)throw new ValidationError(`${label}: fecha ISO UTC real.`);return new Date(v).toISOString();};
const FIELDS={hogares:['nombre','ingresosMensualesDeclaradosCent','ahorroDisponibleDeclaradoCent','maxEsfuerzoBp','maxDesplazamientoDiaMin','minSuperficieM2','minDormitorios','prioridades'],viviendas:['hogarId','titulo','zona','referencia','modalidad','alquilerMensualCent','comunidadMensualCent','suministrosMensualesCent','internetMensualCent','seguroMensualCent','transporteMensualCent','otrosMensualesCent','costeInicialInformadoCent','superficieM2','dormitorios','desplazamientoDiaMin','accesibilidad','estabilidadPercibida','estadoShortlist','notas'],visitas:['viviendaId','fecha','nota']};
function strict(body,allowed){if(!body||typeof body!=='object'||Array.isArray(body))throw new ValidationError('Objeto JSON requerido.');const unknown=Object.keys(body).filter(k=>!allowed.includes(k));if(unknown.length)throw new ValidationError(`Propiedades no permitidas: ${unknown.join(', ')}.`);}
function find(state,key,id){const item=state[key].find(x=>x.id===id);if(!item)throw new HttpError(404,'No encontrado.');return item;}
function exists(state,key,id,label){if(typeof id!=='string'||!state[key].some(x=>x.id===id))throw new ValidationError(`${label} no válido.`);return id;}
function movement(state,entidad,entidadId,accion,resumen){state.historial.push({id:randomUUID(),entidad,entidadId,accion,resumen:String(resumen).slice(0,240),at:new Date().toISOString()});}
const entityName=key=>({hogares:'hogar',viviendas:'vivienda',visitas:'visita'}[key]);
function hogarInput(body){if(!body.prioridades||typeof body.prioridades!=='object'||Array.isArray(body.prioridades))throw new ValidationError('Prioridades no válidas.'); strict(body.prioridades,['coste','espacio','movilidad','accesibilidad','estabilidad']); const prioridades=Object.fromEntries(['coste','espacio','movilidad','accesibilidad','estabilidad'].map(k=>[k,int(body.prioridades[k],0,100,`Peso ${k}`)])); if(Object.values(prioridades).reduce((a,b)=>a+b,0)!==100)throw new ValidationError('Los pesos deben sumar 100.'); return {nombre:trim(body.nombre,60,'Nombre'),ingresosMensualesDeclaradosCent:int(body.ingresosMensualesDeclaradosCent,1,100000000,'Ingresos'),ahorroDisponibleDeclaradoCent:int(body.ahorroDisponibleDeclaradoCent,0,1000000000,'Ahorro'),maxEsfuerzoBp:int(body.maxEsfuerzoBp,1,10000,'Máximo esfuerzo'),maxDesplazamientoDiaMin:int(body.maxDesplazamientoDiaMin,0,1440,'Máximo desplazamiento'),minSuperficieM2:int(body.minSuperficieM2,1,10000,'Superficie mínima'),minDormitorios:int(body.minDormitorios,0,100,'Dormitorios mínimos'),prioridades};}
function viviendaInput(body,state){exists(state,'hogares',body.hogarId,'Hogar');if(!['vivienda_completa','habitacion'].includes(body.modalidad))throw new ValidationError('Modalidad no válida.');if(!['guardada','comparando','finalista','descartada','no_disponible'].includes(body.estadoShortlist))throw new ValidationError('Estado no válido.');const out={hogarId:body.hogarId,titulo:trim(body.titulo,100,'Título'),zona:trim(body.zona,100,'Zona'),referencia:optional(body.referencia,160,'Referencia'),modalidad:body.modalidad}; for(const key of engine.moneyKeys)out[key]=int(body[key],0,100000000,key); return {...out,costeInicialInformadoCent:int(body.costeInicialInformadoCent,0,1000000000,'Coste inicial'),superficieM2:int(body.superficieM2,1,10000,'Superficie'),dormitorios:int(body.dormitorios,0,100,'Dormitorios'),desplazamientoDiaMin:int(body.desplazamientoDiaMin,0,1440,'Desplazamiento'),accesibilidad:int(body.accesibilidad,0,5,'Accesibilidad'),estabilidadPercibida:int(body.estabilidadPercibida,0,5,'Estabilidad'),estadoShortlist:body.estadoShortlist,notas:optional(body.notas,1000,'Notas')};}
function visitaInput(body,state,currentId){const viviendaId=exists(state,'viviendas',body.viviendaId,'Vivienda'),fecha=iso(body.fecha,'Fecha');if(Date.parse(fecha)>Date.now()&&state.visitas.some(v=>v.id!==currentId&&v.viviendaId===viviendaId&&v.estado==='programada'&&Date.parse(v.fecha)>Date.now()))throw new ConflictError('La vivienda ya tiene una visita futura programada.');return {viviendaId,fecha,nota:optional(body.nota,1000,'Nota')};}
function send(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':data.length});res.end(data);}
function readBody(req){if((req.headers['content-type']||'').split(';')[0].trim().toLowerCase()!=='application/json'){req.resume();throw new HttpError(415,'Envía application/json.');}return new Promise((resolve,reject)=>{let size=0,done=false;const chunks=[];req.on('data',chunk=>{if(done)return;size+=chunk.length;if(size>MAX_BODY){done=true;reject(new HttpError(413,'Cuerpo demasiado grande.'));req.resume();}else chunks.push(chunk);});req.on('end',()=>{if(done)return;try{const body=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!body||typeof body!=='object'||Array.isArray(body))throw new Error();resolve(body);}catch{reject(new HttpError(400,'JSON no válido.'));}});req.on('error',()=>reject(new HttpError(400,'Petición interrumpida.')));});}
function createApp({dataDir=path.join(__dirname,'data')}={}){const resolved=path.resolve(dataDir),store=createStore(resolved);const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), geolocation=(), microphone=()');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");try{const port=server.address().port;if(req.headers.host!==`127.0.0.1:${port}`)throw new HttpError(403,'Acceso permitido solo mediante 127.0.0.1.');const url=new URL(req.url,`http://127.0.0.1:${port}`);
  if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{app:'techojusto-local',instance:createHash('sha256').update(resolved.toLowerCase()).digest('hex').slice(0,16),recovered:store.recovered});
  if(req.method==='GET'&&url.pathname==='/api/state'){const state=store.read();return send(res,200,{...state,analytics:engine.analytics(state,Object.fromEntries(url.searchParams))});}
  let match=url.pathname.match(/^\/api\/viviendas\/([^/]+)\/calculo$/);if(match&&req.method==='GET'){const state=store.read(),v=find(state,'viviendas',match[1]),h=find(state,'hogares',v.hogarId);return send(res,200,engine.calcular(h,v));}
  match=url.pathname.match(/^\/api\/viviendas\/([^/]+)\/transicion$/);if(match&&req.method==='POST'){const body=await readBody(req);strict(body,['a']);const changed=store.update(state=>{const v=find(state,'viviendas',match[1]);if(typeof body.a!=='string'||!engine.canShortlist(v.estadoShortlist,body.a))throw new ConflictError(`No se permite pasar de ${v.estadoShortlist} a ${body.a||'vacío'}.`);const from=v.estadoShortlist;v.estadoShortlist=body.a;v.updatedAt=new Date().toISOString();movement(state,'vivienda',v.id,'cambiar_estado',`${from} → ${body.a}`);return v;});return send(res,200,changed);}
  match=url.pathname.match(/^\/api\/visitas\/([^/]+)\/transicion$/);if(match&&req.method==='POST'){const body=await readBody(req);strict(body,['a','nota']);const changed=store.update(state=>{const v=find(state,'visitas',match[1]);if(typeof body.a!=='string'||!engine.canVisit(v.estado,body.a))throw new ConflictError(`No se permite pasar de ${v.estado} a ${body.a||'vacío'}.`);if(body.a==='realizada'&&Date.parse(v.fecha)>Date.now())throw new ConflictError('No se puede realizar una visita con fecha futura.');const from=v.estado;v.estado=body.a;if(body.nota!==undefined)v.nota=optional(body.nota,1000,'Nota');v.updatedAt=new Date().toISOString();movement(state,'visita',v.id,'cambiar_estado',`${from} → ${body.a}`);return v;});return send(res,200,changed);}
  const collection=url.pathname.match(/^\/api\/(hogares|viviendas|visitas)$/),item=url.pathname.match(/^\/api\/(hogares|viviendas|visitas)\/([^/]+)$/);if(collection){const key=collection[1];if(req.method==='GET')return send(res,200,store.read()[key]);if(req.method==='POST'){const body=await readBody(req);strict(body,FIELDS[key]);const created=store.update(state=>{const now=new Date().toISOString();let values;if(key==='hogares')values=hogarInput(body);if(key==='viviendas')values=viviendaInput(body,state);if(key==='visitas')values=visitaInput(body,state);const entity={id:randomUUID(),...values,...(key==='visitas'?{estado:'programada'}:{}),createdAt:now,updatedAt:now};state[key].push(entity);movement(state,entityName(key),entity.id,key==='visitas'?'programar_visita':'crear',entity.nombre||entity.titulo||'Visita programada');return entity;});return send(res,201,created);}}
  if(item){const key=item[1],id=item[2];if(req.method==='GET')return send(res,200,find(store.read(),key,id));if(req.method==='PATCH'){const body=await readBody(req);strict(body,FIELDS[key]);const changed=store.update(state=>{const entity=find(state,key,id),beforeTotal=key==='viviendas'?engine.totalMensual(entity):null;let merged={...entity,...body},values;if(key==='hogares')values=hogarInput(merged);if(key==='viviendas'){if(body.estadoShortlist!==undefined&&body.estadoShortlist!==entity.estadoShortlist)throw new ConflictError('Usa la transición de shortlist.');if(body.hogarId!==undefined&&body.hogarId!==entity.hogarId)throw new ConflictError('No se puede cambiar el vínculo histórico de hogar.');values=viviendaInput(merged,state);}if(key==='visitas'){if(body.viviendaId!==undefined&&body.viviendaId!==entity.viviendaId)throw new ConflictError('No se puede cambiar el vínculo histórico de vivienda.');values=visitaInput(merged,state,id);}Object.assign(entity,values);entity.updatedAt=new Date().toISOString();const afterTotal=key==='viviendas'?engine.totalMensual(entity):null, action=key==='viviendas'&&beforeTotal!==afterTotal?'cambiar_coste':'editar';movement(state,entityName(key),id,action,action==='cambiar_coste'?`Total mensual: ${beforeTotal} → ${afterTotal} céntimos`:(entity.nombre||entity.titulo||'Registro actualizado'));return entity;});return send(res,200,changed);}if(req.method==='DELETE'){const deleted=store.update(state=>{const entity=find(state,key,id);if(key==='hogares'&&state.viviendas.some(v=>v.hogarId===id))throw new ConflictError('El hogar tiene viviendas asociadas.');if(key==='viviendas'&&state.visitas.some(v=>v.viviendaId===id))throw new ConflictError('La vivienda tiene visitas asociadas.');state[key].splice(state[key].indexOf(entity),1);movement(state,entityName(key),id,'borrar',entity.nombre||entity.titulo||'Registro eliminado');return entity;});return send(res,200,{ok:true,deleted});}}
  if(['GET','HEAD'].includes(req.method)&&STATIC.has(url.pathname)){const [file,type]=STATIC.get(url.pathname),content=fs.readFileSync(path.join(__dirname,'public',file));res.writeHead(200,{'Content-Type':type,'Content-Length':content.length});return res.end(req.method==='HEAD'?undefined:content);}throw new HttpError(404,'No encontrado.');
}catch(error){const status=error instanceof HttpError?error.status:error instanceof ConflictError?409:error instanceof ValidationError?400:500;if(status===500)console.error(error);if(!res.destroyed)send(res,status,{error:status===500?'Error interno.':error.message});}});return server;}
if(require.main===module){const port=process.env.TECHOJUSTO_PORT===undefined?4328:Number(process.env.TECHOJUSTO_PORT),app=createApp({dataDir:process.env.TECHOJUSTO_DATA_DIR||path.join(__dirname,'data')});app.on('error',error=>{console.error(error.code==='EADDRINUSE'?`Puerto ${port} ocupado.`:error.message);process.exitCode=1;});app.listen(port,'127.0.0.1',()=>console.log(`TechoJusto en http://127.0.0.1:${port}\nCtrl+C para cerrar.`));}
module.exports={createApp};
