'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const plain = value => value !== null && typeof value === 'object' && !Array.isArray(value);
const text = (value, max, required = true) => typeof value === 'string' && value.length <= max && (!required || (value.length > 0 && value === value.trim()));
const integer = (value, min, max) => Number.isInteger(value) && value >= min && value <= max;
const iso = value => { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(value)) return false; const match=value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})/),[year,month,day,hour,minute,second]=match.slice(1).map(Number); if(hour>23||minute>59||second>59)return false; const parsed=new Date(Date.UTC(year,month-1,day,hour,minute,second)); return parsed.getUTCFullYear()===year&&parsed.getUTCMonth()===month-1&&parsed.getUTCDate()===day; };
class ValidationError extends Error {}
function createSeed() {
  const hogar = '10000000-0000-4000-8000-000000000001', now = '2026-09-24T08:00:00.000Z';
  const ids = ['20000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000003'];
  return { version: 1,
    hogares: [{ id: hogar, nombre: 'Proyecto hogar tranquilo', ingresosMensualesDeclaradosCent: 330000, ahorroDisponibleDeclaradoCent: 500000, maxEsfuerzoBp: 3500, maxDesplazamientoDiaMin: 60, minSuperficieM2: 70, minDormitorios: 2, prioridades: { coste: 35, espacio: 20, movilidad: 15, accesibilidad: 15, estabilidad: 15 }, createdAt: now, updatedAt: now }],
    viviendas: [
      { id: ids[0], hogarId: hogar, titulo: 'Centro compacto', zona: 'Centro', referencia: 'Portal local · C-104', modalidad: 'vivienda_completa', alquilerMensualCent: 95000, comunidadMensualCent: 6000, suministrosMensualesCent: 12000, internetMensualCent: 3000, seguroMensualCent: 1000, transporteMensualCent: 6000, otrosMensualesCent: 0, costeInicialInformadoCent: 280000, superficieM2: 58, dormitorios: 2, desplazamientoDiaMin: 25, accesibilidad: 3, estabilidadPercibida: 3, estadoShortlist: 'comparando', notas: 'Céntrico y práctico; comprobar aislamiento.', createdAt: now, updatedAt: now },
      { id: ids[1], hogarId: hogar, titulo: 'Periferia amplia', zona: 'Periferia norte', referencia: 'Agencia de barrio · P-82', modalidad: 'vivienda_completa', alquilerMensualCent: 85000, comunidadMensualCent: 5000, suministrosMensualesCent: 15000, internetMensualCent: 3000, seguroMensualCent: 1000, transporteMensualCent: 18000, otrosMensualesCent: 2000, costeInicialInformadoCent: 250000, superficieM2: 82, dormitorios: 3, desplazamientoDiaMin: 80, accesibilidad: 5, estabilidadPercibida: 4, estadoShortlist: 'comparando', notas: 'Más espacio; revisar trayecto diario.', createdAt: now, updatedAt: now },
      { id: ids[2], hogarId: hogar, titulo: 'Barrio equilibrado', zona: 'Barrio del Parque', referencia: 'Particular · B-72', modalidad: 'vivienda_completa', alquilerMensualCent: 82000, comunidadMensualCent: 5500, suministrosMensualesCent: 12000, internetMensualCent: 3000, seguroMensualCent: 1000, transporteMensualCent: 6000, otrosMensualesCent: 1500, costeInicialInformadoCent: 310000, superficieM2: 72, dormitorios: 2, desplazamientoDiaMin: 45, accesibilidad: 4, estabilidadPercibida: 4, estadoShortlist: 'finalista', notas: 'Buen equilibrio según datos declarados.', createdAt: now, updatedAt: now }
    ],
    visitas: [
      { id: '30000000-0000-4000-8000-000000000001', viviendaId: ids[1], fecha: '2026-09-26T17:30:00.000Z', estado: 'programada', nota: 'Preguntar por consumos reales.', createdAt: now, updatedAt: now },
      { id: '30000000-0000-4000-8000-000000000002', viviendaId: ids[2], fecha: '2026-09-23T17:30:00.000Z', estado: 'realizada', nota: 'Buena luz natural; ventanas correctas.', createdAt: now, updatedAt: now }
    ],
    historial: [{ id: '40000000-0000-4000-8000-000000000001', entidad: 'hogar', entidadId: hogar, accion: 'crear', resumen: 'Escenario inicial creado.', at: now }]
  };
}
function unique(items) { const ids = new Set(); for (const item of items) { if (!plain(item) || !UUID.test(item.id) || ids.has(item.id)) return null; ids.add(item.id); } return ids; }
function exactKeys(object, keys) { return plain(object) && Object.keys(object).length === keys.length && keys.every(key => Object.hasOwn(object, key)); }
function validState(state) {
  if (!plain(state) || state.version !== 1 || !Array.isArray(state.hogares) || !Array.isArray(state.viviendas) || !Array.isArray(state.visitas) || !Array.isArray(state.historial)) return false;
  const hids = unique(state.hogares), vids = unique(state.viviendas), visids = unique(state.visitas), mids = unique(state.historial); if (!hids || !vids || !visids || !mids) return false;
  for (const h of state.hogares) { const p=h.prioridades; if (!text(h.nombre,60)||!integer(h.ingresosMensualesDeclaradosCent,1,100000000)||!integer(h.ahorroDisponibleDeclaradoCent,0,1000000000)||!integer(h.maxEsfuerzoBp,1,10000)||!integer(h.maxDesplazamientoDiaMin,0,1440)||!integer(h.minSuperficieM2,1,10000)||!integer(h.minDormitorios,0,100)||!exactKeys(p,['coste','espacio','movilidad','accesibilidad','estabilidad'])||!Object.values(p).every(x=>integer(x,0,100))||Object.values(p).reduce((a,b)=>a+b,0)!==100||!iso(h.createdAt)||!iso(h.updatedAt)) return false; }
  for (const v of state.viviendas) { if (!hids.has(v.hogarId)||!text(v.titulo,100)||!text(v.zona,100)||!text(v.referencia,160,false)||!['vivienda_completa','habitacion'].includes(v.modalidad)||!['alquilerMensualCent','comunidadMensualCent','suministrosMensualesCent','internetMensualCent','seguroMensualCent','transporteMensualCent','otrosMensualesCent'].every(k=>integer(v[k],0,100000000))||!integer(v.costeInicialInformadoCent,0,1000000000)||!integer(v.superficieM2,1,10000)||!integer(v.dormitorios,0,100)||!integer(v.desplazamientoDiaMin,0,1440)||!integer(v.accesibilidad,0,5)||!integer(v.estabilidadPercibida,0,5)||!['guardada','comparando','finalista','descartada','no_disponible'].includes(v.estadoShortlist)||!text(v.notas,1000,false)||!iso(v.createdAt)||!iso(v.updatedAt)) return false; }
  for (const v of state.visitas) if (!vids.has(v.viviendaId)||!iso(v.fecha)||!['programada','realizada','cancelada'].includes(v.estado)||!text(v.nota,1000,false)||!iso(v.createdAt)||!iso(v.updatedAt)) return false;
  const futureScheduled = new Set(); for (const v of state.visitas.filter(v=>v.estado==='programada'&&Date.parse(v.fecha)>Date.now())) { if (futureScheduled.has(v.viviendaId)) return false; futureScheduled.add(v.viviendaId); }
  for (const m of state.historial) if (!['hogar','vivienda','visita'].includes(m.entidad)||!UUID.test(m.entidadId)||!['crear','editar','borrar','cambiar_estado','cambiar_coste','programar_visita'].includes(m.accion)||!text(m.resumen,240)||!iso(m.at)) return false;
  return true;
}
function atomicWrite(file, state) { const temp=`${file}.${randomUUID()}.tmp`; let fd; try { fd=fs.openSync(temp,'wx',0o600); fs.writeFileSync(fd,`${JSON.stringify(state,null,2)}\n`,'utf8'); fs.fsyncSync(fd); fs.closeSync(fd); fd=undefined; fs.renameSync(temp,file); } finally { if(fd!==undefined) fs.closeSync(fd); if(fs.existsSync(temp)) fs.unlinkSync(temp); } }
function readValid(file){ if(!fs.existsSync(file)) return {missing:true}; try { const state=JSON.parse(fs.readFileSync(file,'utf8')); return validState(state)?{state}:{invalid:true}; } catch(error){ if(error instanceof SyntaxError) return {invalid:true}; throw error; } }
function createStore(dataDir,{seed=createSeed()}={}) { fs.mkdirSync(dataDir,{recursive:true}); const file=path.join(dataDir,'techojusto.json'), backup=path.join(dataDir,'techojusto.backup.json'); const primary=readValid(file); let state,recovered=false; if(primary.state) state=primary.state; else { const previous=readValid(backup); if(previous.state){ if(!primary.missing) fs.copyFileSync(file,`${file}.corrupt-${Date.now()}`); atomicWrite(file,previous.state); state=previous.state; recovered=true; } else if(primary.missing&&previous.missing&&validState(seed)){ state=structuredClone(seed); atomicWrite(backup,state); atomicWrite(file,state); } else throw new Error('Datos ilegibles: principal y respaldo se conservan para revisión manual.'); } return {recovered,paths:{file,backup},read:()=>structuredClone(state),update(mutator){const next=structuredClone(state),result=mutator(next); if(!validState(next)) throw new Error('La actualización produciría datos no válidos.'); atomicWrite(backup,state); atomicWrite(file,next); state=next; return structuredClone(result);}}; }
module.exports={createStore,createSeed,validState,atomicWrite,ValidationError};
